language: python

python:
  - "3.7"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true


script:
- pip install setuptools
- python setup.py build
- python setup.py install
- pip list
